### ISSUE TITLE
Trainer - Basic Profile - Auto-populated fields should be grey out and non editable

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#1]
When we visit the Basic Information page for trainer it shows Email and Time Zone field as Editable and normal entry field. However, they should be non-editable grey out area as they will be auto-populated.
Screen Shot Attached.

![Image](https://user-images.githubusercontent.com/39871181/216746699-83a64fd3-e352-4dbc-9edb-ba45d674661d.jpg)

**Comment by vishal1145** [comment]
Now it has been worked


![Image](https://user-images.githubusercontent.com/12661409/220928066-ee0894ea-3a75-4638-86e8-8343f3687419.png)

**Comment by saknid** [comment]
Testing done, working as expected.
