### ISSUE TITLE
Application - White space on sides can be used

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#10]
When we are accessing application (On any resolution) it shows white space on both sides, which can be used for better presentation of application, pages and functionality.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216777166-6167b26f-7dc5-4aca-acba-0da6bd278c94.jpg)

**Comment by vishal1145** [comment]
There is no more white space on both sides

![Image](https://user-images.githubusercontent.com/12661409/220919301-e90cedec-d7af-491b-b0d7-a6c55058c922.png

**Comment by saknid** [comment]
Testing done working as expected.
