### ISSUE TITLE
Application - Color Coding - When hovered on Save & next button it should show Blue colored text

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#12]
When Save & Next button is in resting position it shows White Text and Blue button while Previous button shows Blue text white button.
When Save & Next button is hovered it shows Black Text and White Button. However, it should show Blue Text and White button when hovered.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216781535-2a9a74bf-0948-458e-8dcb-3d70a3abf31b.jpg)

**Comment by vishal1145** [comment]
Now it has been worked


![Image](https://user-images.githubusercontent.com/12661409/220924617-11ac5bda-cded-4200-a45d-bc71d9f24f5d.png)

**Comment by saknid** [comment]
Testing done, working as expected.
