### ISSUE TITLE
Trainer - Skill & Experience - Change text Skills I am Knowledge in to Skills I have Knowledge in

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#13]
When we visit Trainer's Skill & experience tab it shows section named "Skills I am knowledge in". Update the sentence as "Skills I have knowledge in".

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216782539-d719a75d-8cdc-409e-af0f-f0e3ffbdbfea.jpg)

**Comment by vishal1145** [comment]
Now this sentence are updated


![Image](https://user-images.githubusercontent.com/12661409/220921690-8978a1e2-99e3-470d-abb4-8746529c0824.png)

**Comment by saknid** [comment]
Testing done, grammar changed.
