### ISSUE TITLE
Trainer - Profile - Edit cover image option is missing

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#17]
Edit cover image option is not available for trainer.

**Testcase used:**  TrainerProfile -- TestCase - 54 -- Step - 2

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216828124-8ca17690-e191-42c6-96ca-7c31dcb59869.jpg)

**Comment by vishal1145** [comment]
Now the option are available


![Image](https://user-images.githubusercontent.com/12661409/220921024-766acf3d-0786-4d89-9874-7927405f03f7.png)

**Comment by saknid** [comment]
Testing done, working as expected.
