### ISSUE TITLE
Application - Buttons and their text alignement

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#19]
When we are visiting any page they have buttons as Save & Next, Previous, Submit but their text and buttons area are not properly aligned with each other.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216896896-95ce3f5a-0d73-4bca-ba87-2ccf00196e74.jpg)

**Comment by vishal1145** [comment]
Now these text are properly aligned to each other


![Image](https://user-images.githubusercontent.com/12661409/220920369-72334f77-fdb3-448c-acab-9fe361a39409.png)

**Comment by saknid** [comment]
Testing done, working as expected.
