### ISSUE TITLE
Trainer Profile - Basic Information - Use common font for all of the field labels

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#23]
Page shows some fields label are written as "Language Known" while for some it shows "My role", "Phone number" and "Time zone".

Follow as first letter of every word as capital letter.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/221354079-607f8d84-288a-45ab-9455-7f4bcb3fc91c.png)

**Comment by vishal1145** [comment]
Noe these are align properly

![Image](https://user-images.githubusercontent.com/12661409/221505405-a7ca1ecb-2e5c-467d-b1ba-8d200f5b03ac.png)

**Comment by saknid** [comment]
Testing done, working as expected.
