### ISSUE TITLE
Trainer Profile - Basic Information - Verify button is generating OTP even when Phone Number field is empty

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#24]
Verify button should not send otp if phone number field is empty rather it should show Empty field validation message. 

Testcase - TrainerProfile -- Testcase - 5 -- Step - 11

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/221354476-0d42fc77-b68c-436a-94d3-50cd23816b34.png)

**Comment by vishal1145** [comment]
Now there will be show the validation message
![Image](https://user-images.githubusercontent.com/12661409/221504757-d54bf75d-9460-45b6-9207-7f069340c7eb.png)

**Comment by saknid** [comment]
Testing done, working as expected.
