### ISSUE TITLE
Application - Field and related button hight should be same accross application

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#4]
If any field has associated button such as Phone Number field has Verify button. Then, in such cases field and button height should same.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216775253-727aa222-0ae8-4dab-b3a6-ab44724ebf07.jpg)

**Comment by vishal1145** [comment]
Now the Height of the button is same

![Image](https://user-images.githubusercontent.com/12661409/220914929-3c399030-9474-4add-9c3e-ec3b74e593e3.png)

**Comment by KeepLearning4ever** [comment]
@saknid  This is just a test
