### ISSUE TITLE
Application - Minimize Navbar and Banner Image Gap

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#6]
When we open application (For any user) - It shows gap between Search Bar and Banner image area, which can be minimized which will give better space towards bottom for further uses.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216775905-10619c95-fcb8-4ace-8237-3c19f05b0cef.jpg)

**Comment by vishal1145** [comment]
Now their space are minimized


![Image](https://user-images.githubusercontent.com/12661409/220922394-182eb960-0ca4-4473-8175-b4982821528e.png)

**Comment by saknid** [comment]
Testing done, working as expected.
