### ISSUE TITLE
Trainer - Professional Summary - Delete icon missing from Text Editor

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#7]
Delete icon should be available on Text Editor for Professional Summary Text Areas as per design shared.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216776312-1583b74d-745b-49c7-9c45-58f5ea7ccb7b.jpg)

**Comment by vishal1145** [comment]
Now the delete button is available and worked
![Image](https://user-images.githubusercontent.com/12661409/221557254-e3478d7a-144b-461d-bc4c-249042cd8110.png)

**Comment by Arunideas** [comment]
Can we have a clear icon instead of delete ?

**Comment by saknid** [comment]
Testing done, working as expected.
