### ISSUE TITLE
Trainer - Professional Summary - On Lower resolution (720p to 1024p) Header is shown in 2 rows

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#8]
When we visit Professional Summary page for Trainer profile on lower resolutions it starts showing "Highlight of the experience" header in two rows.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216776644-a29bd578-f830-40c3-8df6-db477d6c9c51.jpg)

**Comment by vishal1145** [comment]
Now the  "Highlight of the experience" header in one row.

![Image](https://user-images.githubusercontent.com/12661409/220916047-105b6db5-94d3-4d94-8b0f-70161db8f1e3.png)
