### ISSUE TITLE
Trainer - Profile Page - Alignment of Profile tab section is not uniform with banner image

### ISSUE THREAD

**Issue by saknid** [Arunideas/React-app#9]
When we go to profile page it shows Banner image but alignment of banner image and profile section is not uniform it is more lined towards left side.

**Screen Shot Attached.**

![Image](https://user-images.githubusercontent.com/39871181/216776947-f9ecbc3f-7079-4fc2-80de-f8513fa2933b.jpg)

**Comment by vishal1145** [comment]
![Image](https://user-images.githubusercontent.com/12661409/220927207-11847ea4-00cf-432a-bbf1-271c3955e0ee.png)

**Comment by saknid** [comment]
Testing done, working as expected.
